document.write("<div class=\"mymenu\">");
document.write("<div class=\"spacermenu\"></div><!--/spacermenu-->");
document.write("<a href=\"home.html\" class=\"menu\">Home</a><br style=\"clear:right;\" />");
document.write("<span class=\"menufake\" >Programs</span>");
document.write("<div style=\"position:relative;top:0px;left:25px;width:100px;height:60px;display:inline;\" align=\"left\"><ul >");
document.write("<li ><a href=\"workshops.php\" class=\"submenu\">Workshops</a></li>");
document.write("<li><a href=\"seminars.html\" class=\"submenu\">Seminars</a></li>");
document.write("<li><a href=\"public_lectures.php\" class=\"submenu\">Public Lectures</a></li>");
document.write("<li><a href=\"essay_2008.html\" class=\"submenu\">Alumni Reunions</a></li>");
document.write("<li><a href=\"lsess.php\" class=\"submenu\">LSE summer school</a></li>");
document.write("<li><a href=\"essay_2008.html\" class=\"submenu\">Competitions</a></li>");
document.write("</ul></div>");
document.write("<a href=\"resources.html\" class=\"menu\">Resources</a><br style=\"clear:right;\" />");
document.write("<a href=\"fundraising.html\" class=\"menu\">Fundraising</a><br style=\"clear:right;\" />");
document.write("<a href=\"alumni_list.php\" class=\"menu\">Alumni</a>");
document.write("<br style=\"clear:right;\" />");
document.write("</div>");
